version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.14  # Use a Node.js Docker image
    steps:
      - checkout  # Check out the repository
      - run:
          name: Debug directory structure
          command: |
            echo "Listing root project directory:"
            ls -la 
            echo "Listing customer-portal directory:"
            ls -la customer-portal 
      - run:
          name: Install dependencies and build project
          command: |
            cd customer-portal  
            npm install 
            npm run build  
      - sonarcloud/scan  # Run the SonarCloud scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
