version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run:
          name: List files in the root directory
          command: |
            ls -al /home/circleci/project  # List the files in the project directory to confirm structure
      - run:
          name: List files in customer-portal
          command: |
            ls -al /home/circleci/project/customer-portal  # List files inside the customer-portal directory
      - run:
          name: Install dependencies in customer-portal
          command: |
            cd /home/circleci/project/customer-portal && npm install  # Install dependencies from customer-portal
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
