version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout  # Checkout your repo to ensure we have the code
      - run:
          name: Install dependencies in customer-portal
          command: |
            cd customer-portal && npm install  
            cd customer-portal && npm run build  
      - sonarcloud/scan  # Run SonarCloud scan after the build

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
