version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0  # SonarCloud official orb

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'  # Use an image that suits your project's language (replace with an appropriate one)
    steps:
      - checkout  # Pull the code from your repository
      - run:
          name: Install dependencies and build project
          command: |
            # Add your project-specific install and build commands here
            # For example, for Node.js, you would use `npm install` and `npm run build`
            npm install
            npm run build
      - sonarcloud/scan  # SonarCloud scan command

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud  # Use the SonarCloud context with the SONAR_TOKEN environment variable
