version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            npm install
            npm run build
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
