version: 2.1

orbs:
  sonarqube: sonarsource/sonarqube@2.0
  node: circleci/node@5.2

jobs:
  custom-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd customer-portal
            npm install
      - sonarqube/scan:
          sonar-project-key: ${SONAR_PROJECT_KEY}
          sonar-organization: ${SONAR_ORG_KEY}
          sonar-host-url: ${SONAR_HOST_URL}
          sonar-login: ${SONAR_TOKEN}

workflows:
  version: 2
  build:
    jobs:
      - custom-test
