version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  custom-test:
    docker:
      - image: cimg/node:16.10  # Use the CircleCI Node.js Docker image
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: List files to verify directory structure
          command: |
            echo "Current directory: $(pwd)"
            ls -alh  # List all files and directories in the current directory
      - run:
          name: Change to customer-portal directory and install dependencies
          command: |
            cd customer-portal  # Move into the customer-portal directory where package.json is located
            npm install --verbose  # Install dependencies
      - run:
          name: Install SonarQube Scanner using apt
          command: |
            sudo apt-get update && sudo apt-get install -y unzip openjdk-11-jre
            curl -L https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.8.0.2856/sonar-scanner-4.8.0.2856-linux.zip -o sonar-scanner.zip
            # Check if the file is downloaded correctly
            ls -lh sonar-scanner.zip
            if [[ ! -s sonar-scanner.zip ]]; then
              echo "SonarQube Scanner zip file is empty or missing. Aborting!";
              exit 1;
            fi
            unzip sonar-scanner.zip -d /opt
            echo 'export PATH=$PATH:/opt/sonar-scanner-4.8.0.2856-linux/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: SonarQube Scan
          command: |
            cd customer-portal  # Ensure you're in the correct directory
            sonar-scanner \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORG_KEY} \
              -Dsonar.sources=. \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

workflows:
  version: 2
  sample:
    jobs:
      - custom-test
