version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:18.0  # Ensure you're using a compatible version of Node.js
    steps:
      - checkout  # Check out the repository to CircleCI workspace
      - run:
          name: List files in the root directory
          command: |
            ls -al /home/circleci/project  # List the files in the project directory to confirm structure
      - run:
          name: List files in customer-portal
          command: |
            ls -al /home/circleci/project/customer-portal  # List files inside the customer-portal directory
      - run:
          name: Install dependencies in customer-portal
          command: |
            cd /home/circleci/project/customer-portal && npm install  # Install dependencies from customer-portal
            cd /home/circleci/project/customer-portal && npm run build  # Build the project inside customer-portal
      - sonarcloud/scan  # Run SonarCloud scan after the build

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
