version: 2.1

orbs:
  node: circleci/node@5

jobs:
  say-hello:
    docker:
      - image: cimg/base:current  # Base image
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    docker:
      - image: cimg/base:current  # Base image for your job
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: |
            curl -sS https://downloads.sonarsource.com/sonar-scanner-cli/sonar-scanner-5.0.1-linux.zip -o sonar-scanner.zip
            unzip sonar-scanner.zip -d /opt
            export PATH=$PATH:/opt/sonar-scanner-5.0.1-linux/bin
            sonar-scanner --version

      - run:
          name: Find files (Optional)
          command: "find ."

      - run:
          name: Run SonarScanner
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is : " $SONAR_BRANCH
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube:
          requires:
            - say-hello
