jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Clear cache and re-run
          command: |
            circleci cache clear
            circleci build
