version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:18.0  # Update Node.js version to >=18
    steps:
      - checkout  # Checkout the repository to CircleCI's workspace
      - run:
          name: List files and verify customer-portal directory
          command: |
            ls -al  # List all files and directories to ensure 'customer-portal' exists
      - run:
          name: Install dependencies in customer-portal
          command: |
            cd customer-portal && npm install  # Change directory and install dependencies
            cd customer-portal && npm run build  # Build the project from the customer-portal directory
      - sonarcloud/scan  # Run SonarCloud scan after the build

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
