version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  custom-test:
    docker:
      - image: cimg/node:16.10  # Use the CircleCI Node.js Docker image
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: List files to verify directory structure
          command: |
            echo "Current directory: $(pwd)"
            ls -alh  # List all files and directories in the current directory
      - run:
          name: Change to customer-portal directory and install dependencies
          command: |
            cd customer-portal  # Move into the customer-portal directory where package.json is located
            npm install --verbose  # Install dependencies
      # - run:
      #     name: Run Tests
      #     command: |
      #       cd customer-portal  # Ensure you're in the correct directory
      #       npm test
      - run:
          name: SonarQube Scan
          command: |
            cd customer-portal  # Ensure you're in the correct directory
            sonar-scanner \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORG_KEY} \
              -Dsonar.sources=. \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

workflows:
  version: 2
  sample:
    jobs:
      - custom-test
