version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  custom-test:
    docker:
      - image: cimg/node:16.10  # Use the CircleCI Node.js Docker image
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Install Dependencies
          command: |
            echo "Checking node and npm versions"
            node -v
            npm -v
            echo "Installing dependencies with verbose output"
            npm install --verbose  # Added --verbose for debugging
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORG_KEY} \
              -Dsonar.sources=. \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

workflows:
  version: 2
  sample:
    jobs:
      - custom-test
