version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout  # Checkout your repo to ensure we have the code
      - run:
          name: Install dependencies in customer-portal
          command: |
            # Make sure we're in the correct directory
            ls -al  # List files to verify the directory structure (optional, for debugging)
            cd customer-portal && npm install  # Navigate to customer-portal directory and install dependencies
            cd customer-portal && npm run build  # Build the project from the customer-portal directory
      - sonarcloud/scan  # Run SonarCloud scan after the build

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
